language: php
 
php:
  - 5.3
  - 5.4
 
before_script:
  - git clone --depth 1 git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp
  - git clone --depth 1 --branch develop git://github.com/CakeDC/Imagine plugins/Imagine
  - cd plugins/Imagine
  - git submodule update --init --recursive
  - cd ../../
  - mv ../FileStorage plugins/FileStorage
  - sh -c "mysql -e 'CREATE DATABASE cakephp_test;'"
  - chmod -R 777 ../cakephp/app/tmp
  - echo "<?php
    class DATABASE_CONFIG {
    public \$test = array(
      'datasource' => 'Database/Mysql',
      'database' => 'cakephp_test',
      'host' => '0.0.0.0',
      'login' => 'travis',
      'persistent' => false,
    );
    }" > ../cakephp/app/Config/database.php
 
script:
  - ./lib/Cake/Console/cake test FileStorage AllFileStorage --stderr
 
notifications:
  email: false